version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env.development
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'municipis'
      MYSQL_ROOT_PASSWORD: 'raices'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  db_data: {}
